export const FETCH_BRANDNAME_REQUEST = "FETCH_BRANDNAME_REQUEST";
export const FETCH_BRANDNAME_SUCCESS = "FETCH_BRANDNAME_SUCCESS";
export const FETCH_BRANDNAME_FAILURE = "FETCH_BRANDNAME_FAILURE";

export const FETCH_APPARELNAME_REQUEST = "FETCH_APPARELNAME_REQUEST";
export const FETCH_APPARELNAME_SUCCESS = "FETCH_APPARELNAME_SUCCESS";
export const FETCH_APPARELNAME_FAILURE = "FETCH_APPARELNAME_FAILURE";

export const FETCH_GENDERNAME_REQUEST = "FETCH_GENDERNAME_REQUEST";
export const FETCH_GENDERNAME_SUCCESS = "FETCH_GENDERNAME_SUCCESS";
export const FETCH_GENDERNAME_FAILURE = "FETCH_GENDERNAME_FAILURE";