export const GET_ALL_REVIEW_REQUEST = "GET_ALL_REVIEW_REQUEST";
export const GET_ALL_REVIEW_FAIL = "GET_ALL_REVIEW_FAIL";
export const GET_ALL_REVIEW_SUCCESS = "GET_ALL_REVIEW_SUCCESS";

export const GET_REVIEW_DETAIL_REQUEST = "GET_REVIEW_DETAIL_REQUEST";
export const GET_REVIEW_DETAIL_FAIL = "GET_REVIEW_DETAIL_FAIL";
export const GET_REVIEW_DETAIL_SUCCESS = "GET_REVIEW_DETAIL_SUCCESS";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";